package com.travelplan.engagement;
import static org.assertj.core.api.Assertions.*;import static org.mockito.Mockito.*;import java.math.BigDecimal;import java.time.LocalDate;import java.util.*;import org.junit.jupiter.api.*;
class EngagementServiceTest {
 SubscriptionRepository subscriptions=mock(SubscriptionRepository.class);FeedbackRepository feedback=mock(FeedbackRepository.class);ReportRepository reports=mock(ReportRepository.class);TravelClient travels=mock(TravelClient.class);RecommendationService recommendations=mock(RecommendationService.class);EngagementService service=new EngagementService(subscriptions,feedback,reports,travels,recommendations);
 @Test void subscribesWithSupportedProviderBeforeCutoff(){UUID user=UUID.randomUUID(),travelId=UUID.randomUUID(),manager=UUID.randomUUID();var travel=new TravelClient.TravelView(travelId,manager,LocalDate.now().plusDays(10),LocalDate.now().plusDays(15),new BigDecimal("250"),20,"PUBLISHED","Paris","Museums","Hotel","Train");when(travels.find(travelId,"Bearer token")).thenReturn(travel);when(subscriptions.findByTravelIdAndTravelerId(travelId,user)).thenReturn(Optional.empty());when(subscriptions.save(any())).thenAnswer(i->i.getArgument(0));var result=service.subscribe(user,new EngagementContracts.SubscribeRequest(travelId,"STRIPE"),"Bearer token");assertThat(result.amount()).isEqualByComparingTo("250");verify(recommendations).participated(user,travel);}
 @Test void enforcesThreeDayCutoff(){UUID id=UUID.randomUUID();when(travels.find(eq(id),anyString())).thenReturn(new TravelClient.TravelView(id,UUID.randomUUID(),LocalDate.now().plusDays(3),LocalDate.now().plusDays(5),BigDecimal.TEN,5,"PUBLISHED","Rome","Food","Hotel","Bus"));assertThatThrownBy(()->service.subscribe(UUID.randomUUID(),new EngagementContracts.SubscribeRequest(id,"PAYPAL"),"token")).hasMessageContaining("three days");}
 @Test void calculatesTravelerStatistics(){UUID user=UUID.randomUUID();Subscription active=new Subscription(UUID.randomUUID(),user,UUID.randomUUID(),"PAYPAL",BigDecimal.TEN);Subscription cancelled=new Subscription(UUID.randomUUID(),user,UUID.randomUUID(),"STRIPE",BigDecimal.ONE);cancelled.cancel();when(subscriptions.findByTravelerIdOrderBySubscribedAtDesc(user)).thenReturn(List.of(active,cancelled));when(feedback.countByTravelerId(user)).thenReturn(1L);when(reports.findByReporterIdOrderByCreatedAtDesc(user)).thenReturn(List.of());var stats=service.travelerStats(user);assertThat(stats.subscriptions()).isEqualTo(2);assertThat(stats.cancellations()).isEqualTo(1);}
 @Test void participantCanLeaveFeedbackOnlyAfterTravel(){UUID user=UUID.randomUUID(),travelId=UUID.randomUUID(),manager=UUID.randomUUID();var travel=new TravelClient.TravelView(travelId,manager,LocalDate.now().minusDays(8),LocalDate.now().minusDays(2),BigDecimal.TEN,5,"COMPLETED","Rome","Food","Hotel","Bus");Subscription subscription=new Subscription(travelId,user,manager,"PAYPAL",BigDecimal.TEN);when(travels.find(travelId,"token")).thenReturn(travel);when(subscriptions.findByTravelIdAndTravelerId(travelId,user)).thenReturn(Optional.of(subscription));when(feedback.existsByTravelIdAndTravelerId(travelId,user)).thenReturn(false);when(feedback.save(any())).thenAnswer(i->i.getArgument(0));var result=service.addFeedback(user,new EngagementContracts.FeedbackRequest(travelId,5,"Excellent"),"token");assertThat(result.rating()).isEqualTo(5);verify(recommendations).rated(user,travel,5);}
 @Test void travelerCannotReportSelf(){UUID user=UUID.randomUUID();assertThatThrownBy(()->service.report(user,new EngagementContracts.ReportRequest(TravelReport.TargetType.TRAVELER,user,null,"reason"))).hasMessageContaining("yourself");}
}
