sonar.projectKey=travel-plan
sonar.projectName=Travel Management System
sonar.sourceEncoding=UTF-8
sonar.sources=gateway/src/main,services/user-service/src/main,services/travel-service/src/main,services/payment-service/src/main
sonar.tests=gateway/src/test,services/user-service/src/test,services/travel-service/src/test,services/payment-service/src/test
sonar.java.binaries=gateway/target/classes,services/user-service/target/classes,services/travel-service/target/classes,services/payment-service/target/classes
sonar.coverage.jacoco.xmlReportPaths=**/target/site/jacoco/jacoco.xml

